#!/usr/bin/env bash
# Prints "Best School" ten times
# Prints "Hi" at the ninth iteration

counter=1

while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
