#!/usr/bin/env bash
# Starts a loop from 1 to 10 and prints "Best School" untill:
# The fourth iteration, it prints "bad luck" instead.
# The eighth iteration, it prints "good luck" instead.

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
