#!/usr/bin/env bash
# configures HAproxy of lb-01 server.
server_config=\
"
	frontend haproxy_balancer
	bind *:80
	mode http
	default_backend webservers

	backend webservers
	balance roundrobin
	server 361159-web-01 100.24.255.78:80 check
	server 2361159-web-0 34.229.161.18:80 check
"
sudo apt install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.5 -y
sudo apt update -y && sudo apt upgrade -y
sudo apt install haproxy -y
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$server_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
