#!/usr/bin/env bash
#   Create a file myscript.pid at /var/run/.
#   Displays "To infinity and beyond" on infinitely.
#   Displays "I hate the kill command" on receiving a SIGTERM.
#   Displays "Y U no love me?!" on receiving a SIGINT.
#   the 'myscript.pid' file is deleted when receiving a SIGQUIT or SIGTERM.

terminat() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminat' SIGTERM
  trap 'terminat' SIGQUIT
done
