#!/usr/bin/env bash
# Displays "To infinity and beyond" every two seconds infinitely
# Displays "I am invincible!!!" at every iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
