#!/usr/bin/env bash
# Displays numbers from 1 to 100, unless
# 1 - the number is a multiple of 3 and 5, prints "FizzBuzz"
# 2 - the number is a multiple of 3, prints "Fizz"
# 3 - the number is a multiple of 5, prints "Buzz"

counter=1

while [ $counter -le 100 ]
do
	if [ $((counter % 3)) -eq 0 ] && [ $((counter % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((counter % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((counter % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
	((counter++))
done
