#!/usr/bin/env bash
# Starts a loop from 1 to 20 and prints current iteration number, except:
# At the fourth iteration, prints "bad luck from China".
# At the ninth iteration, prints "bad luck from Japan".
# At the seventeenth iteration, prints "bad luck from Italy".

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		"4") echo "bad luck from China"
			;;

		"9") echo "bad luck from Japan"
			;;

		"17") echo "Italian"
			;;
	esac
	((counter++))
done
